package com.ivanfrias.fifaPlayers.Models.enums;

import lombok.Getter;

@Getter
public enum CountryEnum {
    INDONESIA("Indonesia"),
    VENEZUELA("Venezuela"),
    CAMEROON("Cameroon"),
    LUXEMBOURG("Luxembourg"),
    CZECH_REPUBLIC("Czech Republic"),
    SWEDEN("Sweden"),
    UGANDA("Uganda"),
    MONTENEGRO("Montenegro"),
    JORDAN("Jordan"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    KOREA_DPR("Korea DPR"),
    UZBEKISTAN("Uzbekistan"),
    FINLAND("Finland"),
    FYR_MACEDONIA("FYR Macedonia"),
    PORTUGAL("Portugal"),
    MALTA("Malta"),
    COLOMBIA("Colombia"),
    ALBANIA("Albania"),
    WALES("Wales"),
    GRENADA("Grenada"),
    SAUDI_ARABIA("Saudi Arabia"),
    UKRAINE("Ukraine"),
    CUBA("Cuba"),
    LATVIA("Latvia"),
    NORTHERN_IRELAND("Northern Ireland"),
    ALGERIA("Algeria"),
    FRANCE("France"),
    CAPE_VERDE("Cape Verde"),
    SLOVAKIA("Slovakia"),
    ISRAEL("Israel"),
    SYRIA("Syria"),
    KENYA("Kenya"),
    GHANA("Ghana"),
    SENEGAL("Senegal"),
    ZAMBIA("Zambia"),
    CENTRAL_AFRICAN_REP("Central African Rep."),
    ICELAND("Iceland"),
    KUWAIT("Kuwait"),
    HONG_KONG("Hong Kong"),
    MADAGASCAR("Madagascar"),
    SIERRA_LEONE("Sierra Leone"),
    LIBERIA("Liberia"),
    ANTIGUA_AND_BARBUDA("Antigua & Barbuda"),
    PHILIPPINES("Philippines"),
    BENIN("Benin"),
    UNITED_STATES("United States"),
    CYPRUS("Cyprus"),
    GUINEA("Guinea"),
    KOREA_REPUBLIC("Korea Republic"),
    TURKEY("Turkey"),
    NIGERIA("Nigeria"),
    RWANDA("Rwanda"),
    BOSNIA_HERZEGOVINA("Bosnia Herzegovina"),
    ZIMBABWE("Zimbabwe"),
    GUAM("Guam"),
    COMOROS("Comoros"),
    NEW_CALEDONIA("New Caledonia"),
    ARMENIA("Armenia"),
    BELARUS("Belarus"),
    SCOTLAND("Scotland"),
    NETHERLANDS("Netherlands"),
    GABON("Gabon"),
    PARAGUAY("Paraguay"),
    AUSTRALIA("Australia"),
    SERBIA("Serbia"),
    ANGOLA("Angola"),
    LIBYA("Libya"),
    SPAIN("Spain"),
    CONGO("Congo"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    GEORGIA("Georgia"),
    BELGIUM("Belgium"),
    BURUNDI("Burundi"),
    CURACAO("Curacao"),
    MONTSERRAT("Montserrat"),
    THAILAND("Thailand"),
    DR_CONGO("DR Congo"),
    TOGO("Togo"),
    BURKINA_FASO("Burkina Faso"),
    FAROE_ISLANDS("Faroe Islands"),
    EL_SALVADOR("El Salvador"),
    ITALY("Italy"),
    URUGUAY("Uruguay"),
    OMAN("Oman"),
    FIJI("Fiji"),
    GERMANY("Germany"),
    ERITREA("Eritrea"),
    CANADA("Canada"),
    BARBADOS("Barbados"),
    BERMUDA("Bermuda"),
    NAMIBIA("Namibia"),
    ARGENTINA("Argentina"),
    LIECHTENSTEIN("Liechtenstein"),
    ENGLAND("England"),
    AZERBAIJAN("Azerbaijan"),
    SLOVENIA("Slovenia"),
    GREECE("Greece"),
    EGYPT("Egypt"),
    AFGHANISTAN("Afghanistan"),
    REPUBLIC_OF_IRELAND("Republic of Ireland"),
    INDIA("India"),
    CHAD("Chad"),
    IRAN("Iran"),
    CHILE("Chile"),
    GAMBIA("Gambia"),
    ESTONIA("Estonia"),
    VIETNAM("Vietnam"),
    SURINAME("Suriname"),
    SOUTH_AFRICA("South Africa"),
    PERU("Peru"),
    KAZAKHSTAN("Kazakhstan"),
    ST_KITTS_NEVIS("St Kitts Nevis"),
    JAPAN("Japan"),
    KOSOVO("Kosovo"),
    IVORY_COAST("Ivory Coast"),
    DENMARK("Denmark"),
    JAMAICA("Jamaica"),
    IRAQ("Iraq"),
    CHINA_PR("China PR"),
    MAURITANIA("Mauritania"),
    MOZAMBIQUE("Mozambique"),
    SWITZERLAND("Switzerland"),
    GUINEA_BISSAU("Guinea Bissau"),
    ECUADOR("Ecuador"),
    NEW_ZEALAND("New Zealand"),
    HUNGARY("Hungary"),
    RUSSIA("Russia"),
    HONDURAS("Honduras"),
    NORWAY("Norway"),
    ROMANIA("Romania"),
    BRAZIL("Brazil"),
    TRINIDAD_AND_TOBAGO("Trinidad & Tobago"),
    AUSTRIA("Austria"),
    GUATEMALA("Guatemala"),
    BOLIVIA("Bolivia"),
    SAO_TOME_AND_PRINCIPE("São Tomé & Príncipe"),
    ETHIOPIA("Ethiopia"),
    PANAMA("Panama"),
    SOUTH_SUDAN("South Sudan"),
    YEMEN("Yemen"),
    LITHUANIA("Lithuania"),
    BULGARIA("Bulgaria"),
    CROATIA("Croatia"),
    TUNISIA("Tunisia"),
    SUDAN("Sudan"),
    MALI("Mali"),
    MOROCCO("Morocco"),
    MOLDOVA("Moldova"),
    NICARAGUA("Nicaragua"),
    MEXICO("Mexico"),
    GUYANA("Guyana"),
    PALESTINE("Palestine"),
    TANZANIA("Tanzania"),
    POLAND("Poland"),
    COSTA_RICA("Costa Rica"),
    ST_LUCIA("St Lucia"),
    HAITI("Haiti"),
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    ANDORRA("Andorra");

    private final String value;

    CountryEnum(String value){
        this.value=value;
    }
}
